# created on 6/16
# this step turns multiple json files generated by last step, into csv format
# To adapt to different instruction following format

import os
import csv
import glob
from tqdm import tqdm
import json

# Get the path of the current script file
current_folder = os.path.dirname(os.path.abspath(__file__))

# Path to the folder containing JSON files
folder_path = os.path.join(current_folder, 'New Folder')

# Path to the output CSV file in the same folder as the script
output_csv_path = os.path.join(current_folder, 'qa_concat.csv')

# Retrieve the list of JSON files
json_files = glob.glob(os.path.join(folder_path, '*.json'))
total_files = len(json_files)

# List to store the extracted question-answer pairs
qa_pairs = []

# Use tqdm to display the progress bar
with tqdm(total=total_files, desc='Processing') as pbar:
    for file_path in json_files:
        with open(file_path, 'r', encoding='utf-8') as file:
            data = json.load(file)

            # Extract the question-answer pairs
            for qa_pair in data['4']['qa_pairs']:
                question = qa_pair['question'].replace('\n', ' ')
                answer = qa_pair['answer'].replace('\n', ' ')
                qa_pairs.append((question, answer))

        pbar.update(1)  # Update the progress bar

# Write the question-answer pairs to a CSV file
with open(output_csv_path, 'w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['question', 'answer'])  # Write the header
    writer.writerows(qa_pairs)

print(f"CSV file '{output_csv_path}' has been created.")

